### ISSUE TITLE
Maybe support for linux & co?

### ISSUE THREAD

**Issue by xSillusx** [xSillusx/ImageScraper#19]
Ive never read into that kind of stuff. (Compiling from Windows to another platform)
Is it even possible with C# and .NET ?
Help is appreciated.

**Comment by AidanFray** [comment]
For this ".NET Core" might be a good idea, however, it's a little new and library support is lacking. Like for example, I'm unsure if "System.Windows.Forms" is supported, I'll take a look

**Comment by dabutvin** [comment]
You can try to run on mono for this.
http://www.mono-project.com/docs/gui/winforms/

**Comment by xSillusx** [comment]
Refactoring process, Issue is obsolete now
