### ISSUE TITLE
Multiple Websites throw scriptErrors

### ISSUE THREAD

**Issue by xSillusx** [xSillusx/ImageScraper#21]
These websites are still getting dumped, but they throw script errors and if you rush trough them by hitting "yes" about the question if you want to proceed running the script its all good. But the process is a bit annoying.

**Comment by dabutvin** [comment]
do you have an example to test with?

I'm prettry sure we just have to set this to true 
https://msdn.microsoft.com/en-us/library/system.windows.forms.webbrowser.scripterrorssuppressed%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Comment by xSillusx** [comment]
Hey, i tested it with this website: https://www.pokewiki.de/Pok%C3%A9mon-Liste maybe you have the same outcome.

**Comment by xSillusx** [comment]
Okay I implemented it, maybe its in the wrong place tho, but it works. Please look over it and tell me if it okay there.

**Comment by AidanFray** [comment]
Any more problems with this, did the line below solved the issue?
https://github.com/xSillusx/ImageScraper/blob/7e061e5aaf2da714ffa421ae963828fe80997798/ImageScraper/Form1.cs#L40

**Comment by xSillusx** [comment]
Yes, there are no scripterrors showing to the user anymore

**Comment by xSillusx** [comment]
Refactoring process, Issue is obsolete now
