### ISSUE TITLE
Dumping more than one time

### ISSUE THREAD

**Issue by xSillusx** [xSillusx/ImageScraper#23]
I dont know what causes it, but currently the dump is being made more than once.
EX: You hit dump, it dumps, it finishes, it restarts the whole process.
It looks like its doing that 4 to 5 times or more.

**Comment by xSillusx** [comment]
it seems like it does this pretty random...sometimes it does it, sometimes it doesnt do it...weird

**Comment by dabutvin** [comment]
This is likely from the navigated complete event being fired multiple times. Could have something to do with the threading.

**Comment by AidanFray** [comment]
Was this issue occurring before threading was added? I remember seeing this issue before making a pull request for the threading patch but I could be wrong.

@xSillusx Do you know a way to recreate this bug, maybe using the same websites or clicking a certain number of times?

**Comment by xSillusx** [comment]
It just occures, ony many differnet websites. I just enter the website, it dumps it, and right after it does it again multiple times

**Comment by AidanFray** [comment]
Do you have an exact link I can use? I just wanna recreate the bug to see what is occurring

**Comment by xSillusx** [comment]
For exmaple: https://www.reddit.com/ does this on my machine. Maybe it will do it on yours too.

**Comment by AidanFray** [comment]
Okay thank you, I'll look into it

**Comment by AidanFray** [comment]
Ah intresting, my web knowledge is lacking, what's an iframe and why does it affect the scraping?

**Comment by dabutvin** [comment]
an iframe is like a webpage inside of a webpage.
The documentCompleted event fires for this inner frame and all the frames in that frame.

I'll push a fix that waits for readystate instead and then calls document ready only once
