### ISSUE TITLE
Loading in the filter twice

### ISSUE THREAD

**Issue by AidanFray** [xSillusx/ImageScraper#28]
The filter is loaded in twice, once when the program loads and every time the dump button is clicked

https://github.com/xSillusx/ImageScraper/blob/2de0cf11c2d8c181d7669206dd2ce135615d61ca/ImageScraper/Form1.cs#L110

https://github.com/xSillusx/ImageScraper/blob/2de0cf11c2d8c181d7669206dd2ce135615d61ca/ImageScraper/Form1.cs#L40

**Comment by xSillusx** [comment]
I think i had a tought about that...but I dont really remember when iam being hoenst lol
The one in the form_load can be erased when iam correct. I will do it and commit real fast.

**Comment by xSillusx** [comment]
solved in (https://github.com/xSillusx/ImageScraper/commit/7e061e5aaf2da714ffa421ae963828fe80997798)
