### ISSUE TITLE
Improve structure of library

### ISSUE THREAD

**Issue by PsychoPflanze** [xSillusx/ImageScraper#34]
https://github.com/xSillusx/ImageScraper/blob/e2606fa53e1d42d6bf31e4747596706e7b30b3da/LibImageScraper/Logic/OnlineHTMLScraper.cs#L33

This is an example of a weirdly structured part of the library. Normally the Scrape function should return a result, rather than having to run it, and then get the result.

**Comment by xSillusx** [comment]
https://github.com/xSillusx/ImageScraper/commit/cd2f5d2aa8bdb0fff138e7fe38754a5f2b7cbbba
