### ISSUE TITLE
Don't split the library by file types

### ISSUE THREAD

**Issue by PsychoPflanze** [xSillusx/ImageScraper#36]
In general it makes more sense to structure the library so it's easier to access features. For example if you want to use the feature `OnlineHTMLScraper`, you import `LibraryName.OnlineHTMLScraper`, but when you need the `Dump` class the feature returns, you would have to import `Models.Dump` as well, when `Dump` is in the same namespace as `OnlineHTMLScraper`, you could import both of them with just one import.

Also, if dump is a shared class, in case there are different scrapers. Think about putting the scrapers in a sub-namespace as well. E.g. `LibraryName.Scrapers.OnlineHTMLScraper`

**Comment by xSillusx** [comment]
Should be fixed with https://github.com/xSillusx/ImageScraper/commit/cd2f5d2aa8bdb0fff138e7fe38754a5f2b7cbbba
