### ISSUE TITLE
Seperate the dumping process into another thread

### ISSUE THREAD

**Issue by xSillusx** [xSillusx/ImageScraper#4]
When doing that, it would be possible to stop the dumping at some point if the dump is taking too long for you

**Comment by xSillusx** [comment]
+ it currently blocks the UI Thread, so no scrolling in log, or previewing

**Comment by AidanFray** [comment]
I'm keen to take this one, I'll jump on it today if no one else is working on it?

**Comment by xSillusx** [comment]
Yea that would be great. Iam currently doing comments and trying to merge all the stuff that is contibuted. I think Iam close to finishing the merging. I will commit in maybe an hour again all the changes. Then we should all be on the same page again ^^

**Comment by xSillusx** [comment]
solved in https://github.com/xSillusx/ImageScraper/pull/24/files

**Comment by AidanFray** [comment]
#26 Seemed to have removed part of the threading, the program seems to not be threaded anymore?
