### ISSUE TITLE
100% success rate please

### ISSUE THREAD

**Issue by xSillusx** [xSillusx/ImageScraper#9]
make it so all websites can be scraped.
At this point, some websites i tested out are proteted against scraping (throwing remoteserver errors)

**Comment by AidanFray** [comment]
@xSillusx Would you try the new pull request with some websites know didn't work before to see if the new code fixes some things

**Comment by xSillusx** [comment]
I will look into it in a few hours. Currently no Computer available. But I really appreciate your effort so far :)

**Comment by xSillusx** [comment]
As far as I can tell, the sites still throw a remoteserver error, I will look more into it....maybe I should start reading the exact exception it is throwing and not just the title....will update with maybe an error code or something like that in a few minutes 👍

**Comment by AidanFray** [comment]
No worries, It could be a multitude of issues we just need to add better exception handling for when it finds a website it doesn't like or can't read

**Comment by xSillusx** [comment]
Hey, this issue can be closed due to this contribution https://github.com/xSillusx/ImageScraper/pull/15
fixes it.
